### Common

spring:

  application:
    name: IotPlatformAPI
  profiles:
    active: dev
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

app:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: iot
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.unloadbrain.assignement.qardio.util.ScriptDataMessageDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.unloadbrain.assignement.qardio.util.ScriptDataMessageSerializer
    topic:
      script-: TrackScript

  influxdb:
    url: http://localhost:8086
    user: admin
    pass: admin
    database: data
    retention-policy: autogen
    read-timeout-in-seconds: 100

logging:
  level:
    root: INFO

---

### Dev profile

spring:
  profiles: dev

logging:
  level:
    com.unloadbrain: DEBUG

---

### Prod profile

spring:
  profiles: prod

logging:
  level:
    com.unloadbrain: INFO

---

### Integration test profile

spring:
  profiles: it
  main:
    allow-bean-definition-overriding: true






